<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ include file="../../include/lotteheader.jsp"%>
			<h1>DOOSAN</h1>
			<h1>투수</h1>
			<table>
				<thead>
					<tr>
						<th>등번호</th>
						<th>선수명</th>
						<th>포지션</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>1</td>					
						<td>박치국</td>					
						<td>중간계투</td>					
					</tr>
				</tbody>
			</table>
			<h1>내야수</h1>
			<table>
				<thead>
					<tr>
						<th>등번호</th>
						<th>선수명</th>
						<th>포지션</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>13</td>					
						<td>허경민</td>					
						<td>3루수</td>					
					</tr>
				</tbody>
			</table>
			<h1>외야수</h1>
			<table>
				<thead>
					<tr>
						<th>등번호</th>
						<th>선수명</th>
						<th>포지션</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>11</td>					
						<td>로하스</td>					
						<td>우익수</td>					
					</tr>
				</tbody>
			</table>
			<h1>포수</h1>
			<table>
				<thead>
					<tr>
						<th>등번호</th>
						<th>선수명</th>
						<th>포지션</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td>25</td>					
						<td>양의지</td>					
						<td>포수</td>					
					</tr>
				</tbody>
			</table>
		</div>
	</main>
</body>
</html>